/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 56
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SPACE = 1,
  aux_sym__entry_suffix_token1 = 2,
  sym_clock_in_marker = 3,
  sym_clock_out_marker = 4,
  sym_break_marker = 5,
  sym_holiday_marker = 6,
  sym_override_marker = 7,
  aux_sym_simple_date_token1 = 8,
  aux_sym_simple_date_token2 = 9,
  sym_time = 10,
  sym_tz_offset = 11,
  sym__account_char = 12,
  sym_description = 13,
  sym_comment = 14,
  sym__spaces = 15,
  sym__eol = 16,
  sym_source_file = 17,
  sym_session = 18,
  sym_clock_in_entry = 19,
  sym_clock_out_entry = 20,
  sym_break_entry = 21,
  sym_holiday_entry = 22,
  sym_override_entry = 23,
  sym__entry_body = 24,
  sym__entry_suffix = 25,
  sym_simple_date = 26,
  sym_account = 27,
  sym__blank = 28,
  aux_sym_source_file_repeat1 = 29,
  aux_sym_session_repeat1 = 30,
  aux_sym_account_repeat1 = 31,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SPACE] = " ",
  [aux_sym__entry_suffix_token1] = "_entry_suffix_token1",
  [sym_clock_in_marker] = "clock_in_marker",
  [sym_clock_out_marker] = "clock_out_marker",
  [sym_break_marker] = "break_marker",
  [sym_holiday_marker] = "holiday_marker",
  [sym_override_marker] = "override_marker",
  [aux_sym_simple_date_token1] = "simple_date_token1",
  [aux_sym_simple_date_token2] = "simple_date_token2",
  [sym_time] = "time",
  [sym_tz_offset] = "tz_offset",
  [sym__account_char] = "_account_char",
  [sym_description] = "description",
  [sym_comment] = "comment",
  [sym__spaces] = "_spaces",
  [sym__eol] = "_eol",
  [sym_source_file] = "source_file",
  [sym_session] = "session",
  [sym_clock_in_entry] = "clock_in_entry",
  [sym_clock_out_entry] = "clock_out_entry",
  [sym_break_entry] = "break_entry",
  [sym_holiday_entry] = "holiday_entry",
  [sym_override_entry] = "override_entry",
  [sym__entry_body] = "_entry_body",
  [sym__entry_suffix] = "_entry_suffix",
  [sym_simple_date] = "simple_date",
  [sym_account] = "account",
  [sym__blank] = "_blank",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_session_repeat1] = "session_repeat1",
  [aux_sym_account_repeat1] = "account_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [aux_sym__entry_suffix_token1] = aux_sym__entry_suffix_token1,
  [sym_clock_in_marker] = sym_clock_in_marker,
  [sym_clock_out_marker] = sym_clock_out_marker,
  [sym_break_marker] = sym_break_marker,
  [sym_holiday_marker] = sym_holiday_marker,
  [sym_override_marker] = sym_override_marker,
  [aux_sym_simple_date_token1] = aux_sym_simple_date_token1,
  [aux_sym_simple_date_token2] = aux_sym_simple_date_token2,
  [sym_time] = sym_time,
  [sym_tz_offset] = sym_tz_offset,
  [sym__account_char] = sym__account_char,
  [sym_description] = sym_description,
  [sym_comment] = sym_comment,
  [sym__spaces] = sym__spaces,
  [sym__eol] = sym__eol,
  [sym_source_file] = sym_source_file,
  [sym_session] = sym_session,
  [sym_clock_in_entry] = sym_clock_in_entry,
  [sym_clock_out_entry] = sym_clock_out_entry,
  [sym_break_entry] = sym_break_entry,
  [sym_holiday_entry] = sym_holiday_entry,
  [sym_override_entry] = sym_override_entry,
  [sym__entry_body] = sym__entry_body,
  [sym__entry_suffix] = sym__entry_suffix,
  [sym_simple_date] = sym_simple_date,
  [sym_account] = sym_account,
  [sym__blank] = sym__blank,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_session_repeat1] = aux_sym_session_repeat1,
  [aux_sym_account_repeat1] = aux_sym_account_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__entry_suffix_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_clock_in_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_clock_out_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_break_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_holiday_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_override_marker] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_simple_date_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_simple_date_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_time] = {
    .visible = true,
    .named = true,
  },
  [sym_tz_offset] = {
    .visible = true,
    .named = true,
  },
  [sym__account_char] = {
    .visible = false,
    .named = true,
  },
  [sym_description] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__spaces] = {
    .visible = false,
    .named = true,
  },
  [sym__eol] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_session] = {
    .visible = true,
    .named = true,
  },
  [sym_clock_in_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_clock_out_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_break_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_holiday_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_override_entry] = {
    .visible = true,
    .named = true,
  },
  [sym__entry_body] = {
    .visible = false,
    .named = true,
  },
  [sym__entry_suffix] = {
    .visible = false,
    .named = true,
  },
  [sym_simple_date] = {
    .visible = true,
    .named = true,
  },
  [sym_account] = {
    .visible = true,
    .named = true,
  },
  [sym__blank] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_session_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_account_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(35);
      ADVANCE_MAP(
        '\n', 53,
        '\r', 1,
        ' ', 37,
        'O', 43,
        'b', 41,
        'h', 42,
        'i', 39,
        'o', 40,
        '#', 51,
        '*', 51,
        ';', 51,
      );
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(49);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(53);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != '*' &&
          lookahead != ';') ADVANCE(49);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(36);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(27);
      if (lookahead == '/') ADVANCE(28);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(29);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(30);
      END_STATE();
    case 7:
      if (lookahead == '2') ADVANCE(12);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(32);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 10:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(52);
      if (lookahead == '#' ||
          lookahead == '*' ||
          lookahead == ';') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(49);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '3')) ADVANCE(9);
      if (('4' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '3')) ADVANCE(15);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(19);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(22);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(25);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 30:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 33:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != '*' &&
          lookahead != ';') ADVANCE(50);
      END_STATE();
    case 34:
      if (eof) ADVANCE(35);
      ADVANCE_MAP(
        '\n', 53,
        '\r', 1,
        '0', 16,
        '1', 17,
        '2', 11,
        'O', 43,
        'b', 41,
        'h', 42,
        'i', 39,
        'o', 40,
        '\t', 52,
        ' ', 52,
        '#', 51,
        '*', 51,
        ';', 51,
      );
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_SPACE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym__entry_suffix_token1);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_clock_in_marker);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_clock_out_marker);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_break_marker);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_holiday_marker);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_override_marker);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_simple_date_token1);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_simple_date_token2);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_time);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_time);
      if (lookahead == ':') ADVANCE(14);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_tz_offset);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym__account_char);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_description);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != '*' &&
          lookahead != ';') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__spaces);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym__eol);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 34},
  [2] = {.lex_state = 34},
  [3] = {.lex_state = 34},
  [4] = {.lex_state = 34},
  [5] = {.lex_state = 34},
  [6] = {.lex_state = 34},
  [7] = {.lex_state = 34},
  [8] = {.lex_state = 34},
  [9] = {.lex_state = 34},
  [10] = {.lex_state = 34},
  [11] = {.lex_state = 34},
  [12] = {.lex_state = 34},
  [13] = {.lex_state = 34},
  [14] = {.lex_state = 34},
  [15] = {.lex_state = 34},
  [16] = {.lex_state = 34},
  [17] = {.lex_state = 34},
  [18] = {.lex_state = 10},
  [19] = {.lex_state = 10},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 34},
  [25] = {.lex_state = 34},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 10},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 33},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 34},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SPACE] = ACTIONS(1),
    [aux_sym__entry_suffix_token1] = ACTIONS(1),
    [sym_clock_in_marker] = ACTIONS(1),
    [sym_clock_out_marker] = ACTIONS(1),
    [sym_break_marker] = ACTIONS(1),
    [sym_holiday_marker] = ACTIONS(1),
    [sym_override_marker] = ACTIONS(1),
    [sym__account_char] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym__eol] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(40),
    [sym_session] = STATE(2),
    [sym_clock_in_entry] = STATE(4),
    [sym_break_entry] = STATE(2),
    [sym_holiday_entry] = STATE(2),
    [sym_override_entry] = STATE(2),
    [sym__blank] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_clock_in_marker] = ACTIONS(5),
    [sym_break_marker] = ACTIONS(7),
    [sym_holiday_marker] = ACTIONS(9),
    [sym_override_marker] = ACTIONS(11),
    [sym_comment] = ACTIONS(13),
    [sym__spaces] = ACTIONS(15),
    [sym__eol] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(5), 1,
      sym_clock_in_marker,
    ACTIONS(7), 1,
      sym_break_marker,
    ACTIONS(9), 1,
      sym_holiday_marker,
    ACTIONS(11), 1,
      sym_override_marker,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__spaces,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      sym__eol,
    STATE(4), 1,
      sym_clock_in_entry,
    STATE(3), 6,
      sym_session,
      sym_break_entry,
      sym_holiday_entry,
      sym_override_entry,
      sym__blank,
      aux_sym_source_file_repeat1,
  [36] = 10,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      sym_clock_in_marker,
    ACTIONS(28), 1,
      sym_break_marker,
    ACTIONS(31), 1,
      sym_holiday_marker,
    ACTIONS(34), 1,
      sym_override_marker,
    ACTIONS(37), 1,
      sym_comment,
    ACTIONS(40), 1,
      sym__spaces,
    ACTIONS(43), 1,
      sym__eol,
    STATE(4), 1,
      sym_clock_in_entry,
    STATE(3), 6,
      sym_session,
      sym_break_entry,
      sym_holiday_entry,
      sym_override_entry,
      sym__blank,
      aux_sym_source_file_repeat1,
  [72] = 8,
    ACTIONS(5), 1,
      sym_clock_in_marker,
    ACTIONS(48), 1,
      sym_clock_out_marker,
    ACTIONS(50), 1,
      sym__spaces,
    ACTIONS(52), 1,
      sym__eol,
    STATE(6), 1,
      sym_clock_in_entry,
    STATE(11), 1,
      sym_clock_out_entry,
    STATE(5), 3,
      sym_session,
      sym__blank,
      aux_sym_session_repeat1,
    ACTIONS(46), 5,
      ts_builtin_sym_end,
      sym_break_marker,
      sym_holiday_marker,
      sym_override_marker,
      sym_comment,
  [103] = 5,
    ACTIONS(48), 1,
      sym_clock_out_marker,
    STATE(6), 1,
      sym_clock_in_entry,
    STATE(10), 1,
      sym_clock_out_entry,
    STATE(7), 3,
      sym_session,
      sym__blank,
      aux_sym_session_repeat1,
    ACTIONS(54), 8,
      ts_builtin_sym_end,
      sym_clock_in_marker,
      sym_break_marker,
      sym_holiday_marker,
      sym_override_marker,
      sym_comment,
      sym__spaces,
      sym__eol,
  [128] = 8,
    ACTIONS(5), 1,
      sym_clock_in_marker,
    ACTIONS(48), 1,
      sym_clock_out_marker,
    ACTIONS(50), 1,
      sym__spaces,
    ACTIONS(52), 1,
      sym__eol,
    STATE(6), 1,
      sym_clock_in_entry,
    STATE(11), 1,
      sym_clock_out_entry,
    STATE(5), 3,
      sym_session,
      sym__blank,
      aux_sym_session_repeat1,
    ACTIONS(46), 5,
      ts_builtin_sym_end,
      sym_break_marker,
      sym_holiday_marker,
      sym_override_marker,
      sym_comment,
  [159] = 6,
    ACTIONS(58), 1,
      sym_clock_in_marker,
    ACTIONS(61), 1,
      sym__spaces,
    ACTIONS(64), 1,
      sym__eol,
    STATE(6), 1,
      sym_clock_in_entry,
    STATE(7), 3,
      sym_session,
      sym__blank,
      aux_sym_session_repeat1,
    ACTIONS(56), 6,
      ts_builtin_sym_end,
      sym_clock_out_marker,
      sym_break_marker,
      sym_holiday_marker,
      sym_override_marker,
      sym_comment,
  [185] = 1,
    ACTIONS(67), 9,
      ts_builtin_sym_end,
      sym_clock_in_marker,
      sym_clock_out_marker,
      sym_break_marker,
      sym_holiday_marker,
      sym_override_marker,
      sym_comment,
      sym__spaces,
      sym__eol,
  [197] = 1,
    ACTIONS(69), 9,
      ts_builtin_sym_end,
      sym_clock_in_marker,
      sym_clock_out_marker,
      sym_break_marker,
      sym_holiday_marker,
      sym_override_marker,
      sym_comment,
      sym__spaces,
      sym__eol,
  [209] = 1,
    ACTIONS(71), 9,
      ts_builtin_sym_end,
      sym_clock_in_marker,
      sym_clock_out_marker,
      sym_break_marker,
      sym_holiday_marker,
      sym_override_marker,
      sym_comment,
      sym__spaces,
      sym__eol,
  [221] = 1,
    ACTIONS(54), 9,
      ts_builtin_sym_end,
      sym_clock_in_marker,
      sym_clock_out_marker,
      sym_break_marker,
      sym_holiday_marker,
      sym_override_marker,
      sym_comment,
      sym__spaces,
      sym__eol,
  [233] = 1,
    ACTIONS(73), 9,
      ts_builtin_sym_end,
      sym_clock_in_marker,
      sym_clock_out_marker,
      sym_break_marker,
      sym_holiday_marker,
      sym_override_marker,
      sym_comment,
      sym__spaces,
      sym__eol,
  [245] = 1,
    ACTIONS(75), 8,
      ts_builtin_sym_end,
      sym_clock_in_marker,
      sym_break_marker,
      sym_holiday_marker,
      sym_override_marker,
      sym_comment,
      sym__spaces,
      sym__eol,
  [256] = 1,
    ACTIONS(77), 8,
      ts_builtin_sym_end,
      sym_clock_in_marker,
      sym_break_marker,
      sym_holiday_marker,
      sym_override_marker,
      sym_comment,
      sym__spaces,
      sym__eol,
  [267] = 1,
    ACTIONS(23), 8,
      ts_builtin_sym_end,
      sym_clock_in_marker,
      sym_break_marker,
      sym_holiday_marker,
      sym_override_marker,
      sym_comment,
      sym__spaces,
      sym__eol,
  [278] = 1,
    ACTIONS(79), 8,
      ts_builtin_sym_end,
      sym_clock_in_marker,
      sym_break_marker,
      sym_holiday_marker,
      sym_override_marker,
      sym_comment,
      sym__spaces,
      sym__eol,
  [289] = 1,
    ACTIONS(81), 8,
      ts_builtin_sym_end,
      sym_clock_in_marker,
      sym_break_marker,
      sym_holiday_marker,
      sym_override_marker,
      sym_comment,
      sym__spaces,
      sym__eol,
  [300] = 5,
    ACTIONS(83), 1,
      sym__account_char,
    ACTIONS(85), 1,
      sym_comment,
    ACTIONS(87), 1,
      sym__spaces,
    STATE(33), 1,
      sym_account,
    STATE(42), 1,
      sym__entry_suffix,
  [316] = 5,
    ACTIONS(83), 1,
      sym__account_char,
    ACTIONS(87), 1,
      sym__spaces,
    ACTIONS(89), 1,
      sym_comment,
    STATE(33), 1,
      sym_account,
    STATE(49), 1,
      sym__entry_suffix,
  [332] = 4,
    ACTIONS(91), 1,
      anon_sym_SPACE,
    ACTIONS(95), 1,
      sym__account_char,
    STATE(21), 1,
      aux_sym_account_repeat1,
    ACTIONS(93), 2,
      aux_sym__entry_suffix_token1,
      sym__eol,
  [346] = 4,
    ACTIONS(91), 1,
      anon_sym_SPACE,
    ACTIONS(99), 1,
      sym__account_char,
    STATE(22), 1,
      aux_sym_account_repeat1,
    ACTIONS(97), 2,
      aux_sym__entry_suffix_token1,
      sym__eol,
  [360] = 4,
    ACTIONS(101), 1,
      anon_sym_SPACE,
    ACTIONS(106), 1,
      sym__account_char,
    STATE(22), 1,
      aux_sym_account_repeat1,
    ACTIONS(104), 2,
      aux_sym__entry_suffix_token1,
      sym__eol,
  [374] = 2,
    ACTIONS(109), 1,
      anon_sym_SPACE,
    ACTIONS(104), 3,
      aux_sym__entry_suffix_token1,
      sym__account_char,
      sym__eol,
  [383] = 3,
    ACTIONS(111), 1,
      sym_comment,
    ACTIONS(113), 1,
      sym__spaces,
    ACTIONS(115), 1,
      sym__eol,
  [393] = 2,
    STATE(44), 1,
      sym_simple_date,
    ACTIONS(117), 2,
      aux_sym_simple_date_token1,
      aux_sym_simple_date_token2,
  [401] = 3,
    ACTIONS(119), 1,
      anon_sym_SPACE,
    ACTIONS(121), 1,
      sym_tz_offset,
    ACTIONS(123), 1,
      sym__eol,
  [411] = 2,
    ACTIONS(125), 1,
      anon_sym_SPACE,
    STATE(43), 1,
      sym__entry_body,
  [418] = 2,
    ACTIONS(125), 1,
      anon_sym_SPACE,
    STATE(46), 1,
      sym__entry_body,
  [425] = 2,
    ACTIONS(127), 1,
      sym_comment,
    ACTIONS(129), 1,
      sym__eol,
  [432] = 2,
    ACTIONS(125), 1,
      anon_sym_SPACE,
    STATE(36), 1,
      sym__entry_body,
  [439] = 2,
    ACTIONS(125), 1,
      anon_sym_SPACE,
    STATE(51), 1,
      sym__entry_body,
  [446] = 2,
    ACTIONS(125), 1,
      anon_sym_SPACE,
    STATE(37), 1,
      sym__entry_body,
  [453] = 2,
    ACTIONS(131), 1,
      aux_sym__entry_suffix_token1,
    ACTIONS(133), 1,
      sym__eol,
  [460] = 2,
    ACTIONS(133), 1,
      sym__eol,
    ACTIONS(135), 1,
      sym_comment,
  [467] = 2,
    ACTIONS(137), 1,
      anon_sym_SPACE,
    ACTIONS(139), 1,
      sym__eol,
  [474] = 1,
    ACTIONS(141), 1,
      sym__eol,
  [478] = 1,
    ACTIONS(143), 1,
      sym__eol,
  [482] = 1,
    ACTIONS(145), 1,
      sym__eol,
  [486] = 1,
    ACTIONS(129), 1,
      sym__eol,
  [490] = 1,
    ACTIONS(147), 1,
      ts_builtin_sym_end,
  [494] = 1,
    ACTIONS(149), 1,
      anon_sym_SPACE,
  [498] = 1,
    ACTIONS(151), 1,
      sym__eol,
  [502] = 1,
    ACTIONS(153), 1,
      sym__eol,
  [506] = 1,
    ACTIONS(155), 1,
      anon_sym_SPACE,
  [510] = 1,
    ACTIONS(157), 1,
      sym__account_char,
  [514] = 1,
    ACTIONS(159), 1,
      sym__eol,
  [518] = 1,
    ACTIONS(161), 1,
      sym__eol,
  [522] = 1,
    ACTIONS(163), 1,
      sym_description,
  [526] = 1,
    ACTIONS(165), 1,
      sym__eol,
  [530] = 1,
    ACTIONS(167), 1,
      sym_time,
  [534] = 1,
    ACTIONS(169), 1,
      sym__eol,
  [538] = 1,
    ACTIONS(171), 1,
      sym__eol,
  [542] = 1,
    ACTIONS(173), 1,
      sym__eol,
  [546] = 1,
    ACTIONS(175), 1,
      sym_comment,
  [550] = 1,
    ACTIONS(177), 1,
      sym__eol,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 36,
  [SMALL_STATE(4)] = 72,
  [SMALL_STATE(5)] = 103,
  [SMALL_STATE(6)] = 128,
  [SMALL_STATE(7)] = 159,
  [SMALL_STATE(8)] = 185,
  [SMALL_STATE(9)] = 197,
  [SMALL_STATE(10)] = 209,
  [SMALL_STATE(11)] = 221,
  [SMALL_STATE(12)] = 233,
  [SMALL_STATE(13)] = 245,
  [SMALL_STATE(14)] = 256,
  [SMALL_STATE(15)] = 267,
  [SMALL_STATE(16)] = 278,
  [SMALL_STATE(17)] = 289,
  [SMALL_STATE(18)] = 300,
  [SMALL_STATE(19)] = 316,
  [SMALL_STATE(20)] = 332,
  [SMALL_STATE(21)] = 346,
  [SMALL_STATE(22)] = 360,
  [SMALL_STATE(23)] = 374,
  [SMALL_STATE(24)] = 383,
  [SMALL_STATE(25)] = 393,
  [SMALL_STATE(26)] = 401,
  [SMALL_STATE(27)] = 411,
  [SMALL_STATE(28)] = 418,
  [SMALL_STATE(29)] = 425,
  [SMALL_STATE(30)] = 432,
  [SMALL_STATE(31)] = 439,
  [SMALL_STATE(32)] = 446,
  [SMALL_STATE(33)] = 453,
  [SMALL_STATE(34)] = 460,
  [SMALL_STATE(35)] = 467,
  [SMALL_STATE(36)] = 474,
  [SMALL_STATE(37)] = 478,
  [SMALL_STATE(38)] = 482,
  [SMALL_STATE(39)] = 486,
  [SMALL_STATE(40)] = 490,
  [SMALL_STATE(41)] = 494,
  [SMALL_STATE(42)] = 498,
  [SMALL_STATE(43)] = 502,
  [SMALL_STATE(44)] = 506,
  [SMALL_STATE(45)] = 510,
  [SMALL_STATE(46)] = 514,
  [SMALL_STATE(47)] = 518,
  [SMALL_STATE(48)] = 522,
  [SMALL_STATE(49)] = 526,
  [SMALL_STATE(50)] = 530,
  [SMALL_STATE(51)] = 534,
  [SMALL_STATE(52)] = 538,
  [SMALL_STATE(53)] = 542,
  [SMALL_STATE(54)] = 546,
  [SMALL_STATE(55)] = 550,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_session, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_session, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_session_repeat1, 2, 0, 0),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_session_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_session_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_session_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clock_in_entry, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__blank, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_session, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clock_out_entry, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_break_entry, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_holiday_entry, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_override_entry, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_account, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_account, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [101] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_account_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_account_repeat1, 2, 0, 0),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_account_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_account_repeat1, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__entry_suffix, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__entry_body, 4, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__entry_suffix, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__entry_body, 5, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [147] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simple_date, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__entry_body, 6, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__entry_suffix, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__entry_body, 7, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__entry_suffix, 4, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__entry_suffix, 5, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_timeclock(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "timeclock",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
