/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 55
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 33
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SPACE = 1,
  aux_sym__entry_suffix_token1 = 2,
  sym_clock_in_marker = 3,
  sym_clock_out_marker = 4,
  sym_break_marker = 5,
  sym_holiday_marker = 6,
  sym_override_marker = 7,
  aux_sym_simple_date_token1 = 8,
  aux_sym_simple_date_token2 = 9,
  sym_time = 10,
  sym_tz_offset = 11,
  sym__account_char = 12,
  sym_description = 13,
  sym_comment = 14,
  sym__spaces = 15,
  sym__eol = 16,
  sym_source_file = 17,
  sym_session = 18,
  sym__comment_line = 19,
  sym_clock_in_entry = 20,
  sym_clock_out_entry = 21,
  sym_break_entry = 22,
  sym_holiday_entry = 23,
  sym_override_entry = 24,
  sym__entry_body = 25,
  sym__entry_suffix = 26,
  sym_simple_date = 27,
  sym_account = 28,
  sym__blank = 29,
  aux_sym_source_file_repeat1 = 30,
  aux_sym_session_repeat1 = 31,
  aux_sym_account_repeat1 = 32,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SPACE] = " ",
  [aux_sym__entry_suffix_token1] = "_entry_suffix_token1",
  [sym_clock_in_marker] = "clock_in_marker",
  [sym_clock_out_marker] = "clock_out_marker",
  [sym_break_marker] = "break_marker",
  [sym_holiday_marker] = "holiday_marker",
  [sym_override_marker] = "override_marker",
  [aux_sym_simple_date_token1] = "simple_date_token1",
  [aux_sym_simple_date_token2] = "simple_date_token2",
  [sym_time] = "time",
  [sym_tz_offset] = "tz_offset",
  [sym__account_char] = "_account_char",
  [sym_description] = "description",
  [sym_comment] = "comment",
  [sym__spaces] = "_spaces",
  [sym__eol] = "_eol",
  [sym_source_file] = "source_file",
  [sym_session] = "session",
  [sym__comment_line] = "_comment_line",
  [sym_clock_in_entry] = "clock_in_entry",
  [sym_clock_out_entry] = "clock_out_entry",
  [sym_break_entry] = "break_entry",
  [sym_holiday_entry] = "holiday_entry",
  [sym_override_entry] = "override_entry",
  [sym__entry_body] = "_entry_body",
  [sym__entry_suffix] = "_entry_suffix",
  [sym_simple_date] = "simple_date",
  [sym_account] = "account",
  [sym__blank] = "_blank",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_session_repeat1] = "session_repeat1",
  [aux_sym_account_repeat1] = "account_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [aux_sym__entry_suffix_token1] = aux_sym__entry_suffix_token1,
  [sym_clock_in_marker] = sym_clock_in_marker,
  [sym_clock_out_marker] = sym_clock_out_marker,
  [sym_break_marker] = sym_break_marker,
  [sym_holiday_marker] = sym_holiday_marker,
  [sym_override_marker] = sym_override_marker,
  [aux_sym_simple_date_token1] = aux_sym_simple_date_token1,
  [aux_sym_simple_date_token2] = aux_sym_simple_date_token2,
  [sym_time] = sym_time,
  [sym_tz_offset] = sym_tz_offset,
  [sym__account_char] = sym__account_char,
  [sym_description] = sym_description,
  [sym_comment] = sym_comment,
  [sym__spaces] = sym__spaces,
  [sym__eol] = sym__eol,
  [sym_source_file] = sym_source_file,
  [sym_session] = sym_session,
  [sym__comment_line] = sym__comment_line,
  [sym_clock_in_entry] = sym_clock_in_entry,
  [sym_clock_out_entry] = sym_clock_out_entry,
  [sym_break_entry] = sym_break_entry,
  [sym_holiday_entry] = sym_holiday_entry,
  [sym_override_entry] = sym_override_entry,
  [sym__entry_body] = sym__entry_body,
  [sym__entry_suffix] = sym__entry_suffix,
  [sym_simple_date] = sym_simple_date,
  [sym_account] = sym_account,
  [sym__blank] = sym__blank,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_session_repeat1] = aux_sym_session_repeat1,
  [aux_sym_account_repeat1] = aux_sym_account_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__entry_suffix_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_clock_in_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_clock_out_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_break_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_holiday_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_override_marker] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_simple_date_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_simple_date_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_time] = {
    .visible = true,
    .named = true,
  },
  [sym_tz_offset] = {
    .visible = true,
    .named = true,
  },
  [sym__account_char] = {
    .visible = false,
    .named = true,
  },
  [sym_description] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__spaces] = {
    .visible = false,
    .named = true,
  },
  [sym__eol] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_session] = {
    .visible = true,
    .named = true,
  },
  [sym__comment_line] = {
    .visible = false,
    .named = true,
  },
  [sym_clock_in_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_clock_out_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_break_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_holiday_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_override_entry] = {
    .visible = true,
    .named = true,
  },
  [sym__entry_body] = {
    .visible = false,
    .named = true,
  },
  [sym__entry_suffix] = {
    .visible = false,
    .named = true,
  },
  [sym_simple_date] = {
    .visible = true,
    .named = true,
  },
  [sym_account] = {
    .visible = true,
    .named = true,
  },
  [sym__blank] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_session_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_account_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(35);
      ADVANCE_MAP(
        '\n', 53,
        '\r', 1,
        ' ', 37,
        'O', 43,
        'b', 41,
        'h', 42,
        'i', 39,
        'o', 40,
        '#', 51,
        '*', 51,
        ';', 51,
      );
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(49);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(53);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != '*' &&
          lookahead != ';') ADVANCE(49);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(36);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(27);
      if (lookahead == '/') ADVANCE(28);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(29);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(30);
      END_STATE();
    case 7:
      if (lookahead == '2') ADVANCE(12);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(32);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 10:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(52);
      if (lookahead == '#' ||
          lookahead == '*' ||
          lookahead == ';') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(49);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '3')) ADVANCE(9);
      if (('4' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '3')) ADVANCE(15);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(19);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(22);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(25);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 30:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 33:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != '*' &&
          lookahead != ';') ADVANCE(50);
      END_STATE();
    case 34:
      if (eof) ADVANCE(35);
      ADVANCE_MAP(
        '\n', 53,
        '\r', 1,
        '0', 16,
        '1', 17,
        '2', 11,
        'O', 43,
        'b', 41,
        'h', 42,
        'i', 39,
        'o', 40,
        '\t', 52,
        ' ', 52,
        '#', 51,
        '*', 51,
        ';', 51,
      );
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_SPACE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym__entry_suffix_token1);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_clock_in_marker);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_clock_out_marker);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_break_marker);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_holiday_marker);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_override_marker);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_simple_date_token1);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_simple_date_token2);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_time);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_time);
      if (lookahead == ':') ADVANCE(14);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_tz_offset);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym__account_char);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_description);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != '*' &&
          lookahead != ';') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__spaces);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym__eol);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 34},
  [2] = {.lex_state = 34},
  [3] = {.lex_state = 34},
  [4] = {.lex_state = 34},
  [5] = {.lex_state = 34},
  [6] = {.lex_state = 34},
  [7] = {.lex_state = 34},
  [8] = {.lex_state = 34},
  [9] = {.lex_state = 34},
  [10] = {.lex_state = 34},
  [11] = {.lex_state = 34},
  [12] = {.lex_state = 34},
  [13] = {.lex_state = 34},
  [14] = {.lex_state = 34},
  [15] = {.lex_state = 34},
  [16] = {.lex_state = 34},
  [17] = {.lex_state = 34},
  [18] = {.lex_state = 10},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 10},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 34},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 34},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 34},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 10},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 33},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SPACE] = ACTIONS(1),
    [aux_sym__entry_suffix_token1] = ACTIONS(1),
    [sym_clock_in_marker] = ACTIONS(1),
    [sym_clock_out_marker] = ACTIONS(1),
    [sym_break_marker] = ACTIONS(1),
    [sym_holiday_marker] = ACTIONS(1),
    [sym_override_marker] = ACTIONS(1),
    [sym__account_char] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym__eol] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(42),
    [sym_session] = STATE(2),
    [sym__comment_line] = STATE(2),
    [sym_clock_in_entry] = STATE(5),
    [sym_break_entry] = STATE(2),
    [sym_holiday_entry] = STATE(2),
    [sym_override_entry] = STATE(2),
    [sym__blank] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_clock_in_marker] = ACTIONS(5),
    [sym_break_marker] = ACTIONS(7),
    [sym_holiday_marker] = ACTIONS(9),
    [sym_override_marker] = ACTIONS(11),
    [sym_comment] = ACTIONS(13),
    [sym__spaces] = ACTIONS(15),
    [sym__eol] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(5), 1,
      sym_clock_in_marker,
    ACTIONS(7), 1,
      sym_break_marker,
    ACTIONS(9), 1,
      sym_holiday_marker,
    ACTIONS(11), 1,
      sym_override_marker,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__spaces,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      sym__eol,
    STATE(5), 1,
      sym_clock_in_entry,
    STATE(3), 7,
      sym_session,
      sym__comment_line,
      sym_break_entry,
      sym_holiday_entry,
      sym_override_entry,
      sym__blank,
      aux_sym_source_file_repeat1,
  [37] = 10,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      sym_clock_in_marker,
    ACTIONS(28), 1,
      sym_break_marker,
    ACTIONS(31), 1,
      sym_holiday_marker,
    ACTIONS(34), 1,
      sym_override_marker,
    ACTIONS(37), 1,
      sym_comment,
    ACTIONS(40), 1,
      sym__spaces,
    ACTIONS(43), 1,
      sym__eol,
    STATE(5), 1,
      sym_clock_in_entry,
    STATE(3), 7,
      sym_session,
      sym__comment_line,
      sym_break_entry,
      sym_holiday_entry,
      sym_override_entry,
      sym__blank,
      aux_sym_source_file_repeat1,
  [74] = 9,
    ACTIONS(5), 1,
      sym_clock_in_marker,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__spaces,
    ACTIONS(48), 1,
      sym_clock_out_marker,
    ACTIONS(50), 1,
      sym__eol,
    STATE(4), 1,
      sym_clock_in_entry,
    STATE(8), 1,
      sym_clock_out_entry,
    ACTIONS(46), 4,
      ts_builtin_sym_end,
      sym_break_marker,
      sym_holiday_marker,
      sym_override_marker,
    STATE(6), 4,
      sym_session,
      sym__comment_line,
      sym__blank,
      aux_sym_session_repeat1,
  [108] = 9,
    ACTIONS(5), 1,
      sym_clock_in_marker,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__spaces,
    ACTIONS(48), 1,
      sym_clock_out_marker,
    ACTIONS(50), 1,
      sym__eol,
    STATE(4), 1,
      sym_clock_in_entry,
    STATE(8), 1,
      sym_clock_out_entry,
    ACTIONS(46), 4,
      ts_builtin_sym_end,
      sym_break_marker,
      sym_holiday_marker,
      sym_override_marker,
    STATE(6), 4,
      sym_session,
      sym__comment_line,
      sym__blank,
      aux_sym_session_repeat1,
  [142] = 5,
    ACTIONS(48), 1,
      sym_clock_out_marker,
    STATE(4), 1,
      sym_clock_in_entry,
    STATE(13), 1,
      sym_clock_out_entry,
    STATE(7), 4,
      sym_session,
      sym__comment_line,
      sym__blank,
      aux_sym_session_repeat1,
    ACTIONS(52), 8,
      ts_builtin_sym_end,
      sym_clock_in_marker,
      sym_break_marker,
      sym_holiday_marker,
      sym_override_marker,
      sym_comment,
      sym__spaces,
      sym__eol,
  [168] = 7,
    ACTIONS(56), 1,
      sym_clock_in_marker,
    ACTIONS(59), 1,
      sym_comment,
    ACTIONS(62), 1,
      sym__spaces,
    ACTIONS(65), 1,
      sym__eol,
    STATE(4), 1,
      sym_clock_in_entry,
    STATE(7), 4,
      sym_session,
      sym__comment_line,
      sym__blank,
      aux_sym_session_repeat1,
    ACTIONS(54), 5,
      ts_builtin_sym_end,
      sym_clock_out_marker,
      sym_break_marker,
      sym_holiday_marker,
      sym_override_marker,
  [197] = 1,
    ACTIONS(52), 9,
      ts_builtin_sym_end,
      sym_clock_in_marker,
      sym_clock_out_marker,
      sym_break_marker,
      sym_holiday_marker,
      sym_override_marker,
      sym_comment,
      sym__spaces,
      sym__eol,
  [209] = 1,
    ACTIONS(68), 9,
      ts_builtin_sym_end,
      sym_clock_in_marker,
      sym_clock_out_marker,
      sym_break_marker,
      sym_holiday_marker,
      sym_override_marker,
      sym_comment,
      sym__spaces,
      sym__eol,
  [221] = 1,
    ACTIONS(70), 9,
      ts_builtin_sym_end,
      sym_clock_in_marker,
      sym_clock_out_marker,
      sym_break_marker,
      sym_holiday_marker,
      sym_override_marker,
      sym_comment,
      sym__spaces,
      sym__eol,
  [233] = 1,
    ACTIONS(72), 9,
      ts_builtin_sym_end,
      sym_clock_in_marker,
      sym_clock_out_marker,
      sym_break_marker,
      sym_holiday_marker,
      sym_override_marker,
      sym_comment,
      sym__spaces,
      sym__eol,
  [245] = 1,
    ACTIONS(74), 9,
      ts_builtin_sym_end,
      sym_clock_in_marker,
      sym_clock_out_marker,
      sym_break_marker,
      sym_holiday_marker,
      sym_override_marker,
      sym_comment,
      sym__spaces,
      sym__eol,
  [257] = 1,
    ACTIONS(76), 9,
      ts_builtin_sym_end,
      sym_clock_in_marker,
      sym_clock_out_marker,
      sym_break_marker,
      sym_holiday_marker,
      sym_override_marker,
      sym_comment,
      sym__spaces,
      sym__eol,
  [269] = 1,
    ACTIONS(78), 9,
      ts_builtin_sym_end,
      sym_clock_in_marker,
      sym_clock_out_marker,
      sym_break_marker,
      sym_holiday_marker,
      sym_override_marker,
      sym_comment,
      sym__spaces,
      sym__eol,
  [281] = 1,
    ACTIONS(80), 8,
      ts_builtin_sym_end,
      sym_clock_in_marker,
      sym_break_marker,
      sym_holiday_marker,
      sym_override_marker,
      sym_comment,
      sym__spaces,
      sym__eol,
  [292] = 1,
    ACTIONS(82), 8,
      ts_builtin_sym_end,
      sym_clock_in_marker,
      sym_break_marker,
      sym_holiday_marker,
      sym_override_marker,
      sym_comment,
      sym__spaces,
      sym__eol,
  [303] = 1,
    ACTIONS(84), 8,
      ts_builtin_sym_end,
      sym_clock_in_marker,
      sym_break_marker,
      sym_holiday_marker,
      sym_override_marker,
      sym_comment,
      sym__spaces,
      sym__eol,
  [314] = 5,
    ACTIONS(86), 1,
      sym__account_char,
    ACTIONS(88), 1,
      sym_comment,
    ACTIONS(90), 1,
      sym__spaces,
    STATE(27), 1,
      sym_account,
    STATE(50), 1,
      sym__entry_suffix,
  [330] = 4,
    ACTIONS(92), 1,
      anon_sym_SPACE,
    ACTIONS(96), 1,
      sym__account_char,
    STATE(21), 1,
      aux_sym_account_repeat1,
    ACTIONS(94), 2,
      aux_sym__entry_suffix_token1,
      sym__eol,
  [344] = 5,
    ACTIONS(86), 1,
      sym__account_char,
    ACTIONS(90), 1,
      sym__spaces,
    ACTIONS(98), 1,
      sym_comment,
    STATE(27), 1,
      sym_account,
    STATE(44), 1,
      sym__entry_suffix,
  [360] = 4,
    ACTIONS(92), 1,
      anon_sym_SPACE,
    ACTIONS(102), 1,
      sym__account_char,
    STATE(22), 1,
      aux_sym_account_repeat1,
    ACTIONS(100), 2,
      aux_sym__entry_suffix_token1,
      sym__eol,
  [374] = 4,
    ACTIONS(104), 1,
      anon_sym_SPACE,
    ACTIONS(109), 1,
      sym__account_char,
    STATE(22), 1,
      aux_sym_account_repeat1,
    ACTIONS(107), 2,
      aux_sym__entry_suffix_token1,
      sym__eol,
  [388] = 2,
    ACTIONS(112), 1,
      anon_sym_SPACE,
    ACTIONS(107), 3,
      aux_sym__entry_suffix_token1,
      sym__account_char,
      sym__eol,
  [397] = 2,
    STATE(49), 1,
      sym_simple_date,
    ACTIONS(114), 2,
      aux_sym_simple_date_token1,
      aux_sym_simple_date_token2,
  [405] = 3,
    ACTIONS(116), 1,
      anon_sym_SPACE,
    ACTIONS(118), 1,
      sym_tz_offset,
    ACTIONS(120), 1,
      sym__eol,
  [415] = 3,
    ACTIONS(122), 1,
      sym_comment,
    ACTIONS(124), 1,
      sym__spaces,
    ACTIONS(126), 1,
      sym__eol,
  [425] = 2,
    ACTIONS(128), 1,
      aux_sym__entry_suffix_token1,
    ACTIONS(130), 1,
      sym__eol,
  [432] = 2,
    ACTIONS(130), 1,
      sym__eol,
    ACTIONS(132), 1,
      sym_comment,
  [439] = 2,
    ACTIONS(134), 1,
      anon_sym_SPACE,
    ACTIONS(136), 1,
      sym__eol,
  [446] = 2,
    ACTIONS(138), 1,
      sym_comment,
    ACTIONS(140), 1,
      sym__eol,
  [453] = 2,
    ACTIONS(142), 1,
      anon_sym_SPACE,
    STATE(37), 1,
      sym__entry_body,
  [460] = 2,
    ACTIONS(142), 1,
      anon_sym_SPACE,
    STATE(40), 1,
      sym__entry_body,
  [467] = 2,
    ACTIONS(142), 1,
      anon_sym_SPACE,
    STATE(51), 1,
      sym__entry_body,
  [474] = 2,
    ACTIONS(142), 1,
      anon_sym_SPACE,
    STATE(43), 1,
      sym__entry_body,
  [481] = 2,
    ACTIONS(142), 1,
      anon_sym_SPACE,
    STATE(41), 1,
      sym__entry_body,
  [488] = 1,
    ACTIONS(144), 1,
      sym__eol,
  [492] = 1,
    ACTIONS(146), 1,
      sym__eol,
  [496] = 1,
    ACTIONS(148), 1,
      sym__eol,
  [500] = 1,
    ACTIONS(150), 1,
      sym_time,
  [504] = 1,
    ACTIONS(152), 1,
      sym__eol,
  [508] = 1,
    ACTIONS(154), 1,
      sym__eol,
  [512] = 1,
    ACTIONS(156), 1,
      ts_builtin_sym_end,
  [516] = 1,
    ACTIONS(158), 1,
      sym__eol,
  [520] = 1,
    ACTIONS(160), 1,
      sym__eol,
  [524] = 1,
    ACTIONS(162), 1,
      sym__account_char,
  [528] = 1,
    ACTIONS(164), 1,
      sym__eol,
  [532] = 1,
    ACTIONS(166), 1,
      sym_description,
  [536] = 1,
    ACTIONS(168), 1,
      anon_sym_SPACE,
  [540] = 1,
    ACTIONS(170), 1,
      anon_sym_SPACE,
  [544] = 1,
    ACTIONS(172), 1,
      sym__eol,
  [548] = 1,
    ACTIONS(174), 1,
      sym__eol,
  [552] = 1,
    ACTIONS(176), 1,
      sym__eol,
  [556] = 1,
    ACTIONS(178), 1,
      sym_comment,
  [560] = 1,
    ACTIONS(180), 1,
      sym__eol,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 37,
  [SMALL_STATE(4)] = 74,
  [SMALL_STATE(5)] = 108,
  [SMALL_STATE(6)] = 142,
  [SMALL_STATE(7)] = 168,
  [SMALL_STATE(8)] = 197,
  [SMALL_STATE(9)] = 209,
  [SMALL_STATE(10)] = 221,
  [SMALL_STATE(11)] = 233,
  [SMALL_STATE(12)] = 245,
  [SMALL_STATE(13)] = 257,
  [SMALL_STATE(14)] = 269,
  [SMALL_STATE(15)] = 281,
  [SMALL_STATE(16)] = 292,
  [SMALL_STATE(17)] = 303,
  [SMALL_STATE(18)] = 314,
  [SMALL_STATE(19)] = 330,
  [SMALL_STATE(20)] = 344,
  [SMALL_STATE(21)] = 360,
  [SMALL_STATE(22)] = 374,
  [SMALL_STATE(23)] = 388,
  [SMALL_STATE(24)] = 397,
  [SMALL_STATE(25)] = 405,
  [SMALL_STATE(26)] = 415,
  [SMALL_STATE(27)] = 425,
  [SMALL_STATE(28)] = 432,
  [SMALL_STATE(29)] = 439,
  [SMALL_STATE(30)] = 446,
  [SMALL_STATE(31)] = 453,
  [SMALL_STATE(32)] = 460,
  [SMALL_STATE(33)] = 467,
  [SMALL_STATE(34)] = 474,
  [SMALL_STATE(35)] = 481,
  [SMALL_STATE(36)] = 488,
  [SMALL_STATE(37)] = 492,
  [SMALL_STATE(38)] = 496,
  [SMALL_STATE(39)] = 500,
  [SMALL_STATE(40)] = 504,
  [SMALL_STATE(41)] = 508,
  [SMALL_STATE(42)] = 512,
  [SMALL_STATE(43)] = 516,
  [SMALL_STATE(44)] = 520,
  [SMALL_STATE(45)] = 524,
  [SMALL_STATE(46)] = 528,
  [SMALL_STATE(47)] = 532,
  [SMALL_STATE(48)] = 536,
  [SMALL_STATE(49)] = 540,
  [SMALL_STATE(50)] = 544,
  [SMALL_STATE(51)] = 548,
  [SMALL_STATE(52)] = 552,
  [SMALL_STATE(53)] = 556,
  [SMALL_STATE(54)] = 560,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_session, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_session, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_session_repeat1, 2, 0, 0),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_session_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_session_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_session_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_session_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__blank, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comment_line, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clock_in_entry, 3, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clock_out_entry, 3, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_session, 3, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comment_line, 3, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_holiday_entry, 3, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_break_entry, 3, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_override_entry, 3, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_account, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_account, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [104] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_account_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_account_repeat1, 2, 0, 0),
  [109] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_account_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_account_repeat1, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__entry_body, 4, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__entry_suffix, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__entry_suffix, 1, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__entry_body, 5, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [156] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__entry_body, 6, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__entry_suffix, 2, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simple_date, 1, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__entry_body, 7, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__entry_suffix, 4, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__entry_suffix, 5, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_timeclock(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "timeclock",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
